name: TempusEssentials
version: '${project.version}'
main: primalcat.tempus.TempusEssentials
api-version: '1.20'
depend: [PlaceholderAPI, ProtocolLib ]
commands:
  playtime:
    description: Отображает время игрока в игре
    usage: /playtime
  plhide:
    description: Reloads the PL-Hide Plugin
    usage: /plhide reload
