name: TempusEssential
author: PrimalCat
main: primalcat.tempusessential.TempusEssential
website: https://groupez.dev
description: Default plugin developed by GroupeZ
version: 1.0.0
api-version: 1.13
load: STARTUP
depend: [PlaceholderAPI,ProtocolLib]
commands:
  copybook:
    description: Копирует содержимое из подписанной книги в неподписанную книгу.
    usage: /copybook
  playtime:
    description: Отображает время игрока в игре
    usage: /playtime
  setrpnick:
    description: Устанавливает рп никнейм
    usage: /setrpnick
  summonfox:
    description: Summons a tamable fox.
    usage: /summonfox
    permission: tempusessential.summonfox
  spawndragon:
    description: Summon a custom Ender Dragon
    usage: /spawndragon
  ttabname:
    permission: tempusessential.colortabname
    description: "Set your tab name with a gradient."
    usage: "/ttabname #color1 #color2"