name: TempusEssential
author: PrimalCat
main: primalcat.tempusessential.TempusEssential
website: https://groupez.dev
description: Default plugin developed by GroupeZ
version: 1.0.0
api-version: 1.13
load: STARTUP
depend: [PlaceholderAPI,ProtocolLib, AuthMe]
commands:
  copybook:
    description: Копирует содержимое из подписанной книги в неподписанную книгу.
    usage: /copybook
  blackhole:
    description: Creates a black hole at your location.
    usage: /blackhole [duration] [cords]
    permission: tempusessential.blackhole
  playtime:
    description: Отображает время игрока в игре
    usage: /playtime
  setrpnick:
    description: Устанавливает рп никнейм
    usage: /setrpnick
  summonfox:
    description: Summons a tamable fox.
    usage: /summonfox
    permission: tempusessential.summonfox
  spawndragon:
    description: Summon a custom Ender Dragon
    usage: /spawndragon
  ttabname:
    permission: tempusessential.colortabname
    description: "Set your tab name with a gradient."
    usage: "/ttabname #color1 #color2"
  savealllocations:
    description: "Сохраняет местоположения всех онлайн игроков"
    permission: "tempus.saveall"

  removefog:
    description: Удаляет игрока из списка тумана.
    usage: /removefog <игрок>
    permission: fog.remove
    permission-message: У вас нет прав для выполнения этой команды.
  spawncorpse:
    description: spawncorpse
    usage: /spawncorpse

  givemobshard:
    description: givemobshard
    usage: /givemobshard
